### ISSUE TITLE
Create the server

### ISSUE THREAD

**Issue by gdey** [go-spatial/maptoolkit#17]
Add a server component to the atlante command.

Implement the following URLs:
${sheet_name} = 50k | 5k

- [ ]  1.  `GET /sheets/${sheet_name}/mgdid/${mgdid-part}.pdf` this will return the pdf. (Proxy) Should set all appropriate headers

- [x] 2. `GET /sheets/${sheet_name}/info/${lng}/${lat}` 

- [x] 3. `GET /sheets/${sheet_name}/info/mdgid/${mdgid-sheet_number}`

these will return the following JSON:
```js
{
  "mdgid" : string,
  "sheet_number" : null | number,
  "pdf_url":  null | url, // if null, pdf has not be generated
  "last_generated" :  null | date, // last time the pdf was generated
  "last_edited" : date,  // last time the data was edited
  "edited_by" : string, // the person who edited this last
  "series" : string,
  "geo_json" : geo_json // the geo_json of the bounding box.
  "lng" : null | float // the queried lng
  "lat" :  null | float // the queried lat
  "sheet_name": string
}
```
- [x] 4. `POST /sheets/${sheet_name}/mdgid` will cause the pdf generation the job to start. 

expected:

```js
{
   "mdgid" : string,
   "sheet_number" : null | number,
}

```

returned:

```js
{
   "mdgid" : string,
   "sheet_number" : null | number,
   "sheet_name" : string,
   "job_id" : number,
   "status" : "requested" | "started" | "processing" | "compleated",
}
```

- strike__[x] 5. `GET /sheets/${sheet_name}/info/job_id/${job_id}`__
- [x] 5. `GET /jobs/${job_id}/status`

```js
{
   "mdgid" : string,
   "sheet_number" : null | number,
   "sheet_name" : string,
   "job_id" : number,
   "status" : "requested" | "started" | "processing" | "completed",
   "status_description" : string,
}
```

- strike__[ ] 6. `POST /sheets/${sheet_name}/notification` used to notify the server that the pdf has been generated.__
- [x] 6. `POST /jobs/${job_id}/status`

```js
{
   "status" : "started" | "processing" | "completed",
   "status_description" : string,
}
```

- [x] 7. `GET /sheets/` used to get the currently configured sheets.

```js
{
   "sheets" : []{
        "name": string,
        "scale" : number, // the scale in meters -- 5k => 5000; 50k => 50000
        "description":string,
    }
}
```

**Comment by ARolek** [comment]
@gdey while testing I noticed that `pdf_url` goes away if the PDF has not been created yet. It should be `null` rather than omit empty.

**Comment by gdey** [comment]
Removed omit-empty, it will remain now.

**Comment by gdey** [comment]
Moved 1. to #47
