### ISSUE TITLE
Add Notifier Component to the work, and Job management to the Server

### ISSUE THREAD

**Issue by gdey** [go-spatial/maptoolkit#38]
The server needs the job management apis built out as per #17.

The server need the following ends-points built:
* `GET /sheets/${sheet_name}/info/job_id/${job_id}`
* `POST /sheets/${sheet_name}/notification`

These return the state of the job, and provide an end-point for the worker to report the job status.

The system needs a place to store the job information. This will be under the webserver configuration:

```toml
[webserver]
[webserver.jobdb]
    type='postgis'
    # ... params for postgis

```

Initial we will support postgis (and a hardcoded schema) and sqlite

Coorinator Provider interface:

```go
type FieldValues interface{
     field() 
}

type Job interface {
     ID()string
     UpdateField(values ...FieldValues)
}

type Provider interface {
    NewJob(*atlante.Job) (jobID Job,  err error)
    FindJob(jobID string) (job Job, found bool )
}
```

**Comment by ARolek** [comment]
@gdey and interesting idea from @jj0hns0n. Rather than have a defined table schema to write to, maybe we support an SQL statement to run and pass in tokens. This would allow the user to customize where the job data is written, what it's named, etc. etc.

Thoughts?

**Comment by gdey** [comment]
I'd rather start with the hardcoded sql statements, and then we can move toward this once I understand the interface better. Right now it's pretty vague in my head. I don't know the shape of the problem from the management side.
