### ISSUE TITLE
Last edited date in the info api response is hard-coded

### ISSUE THREAD

**Issue by jj0hns0n** [go-spatial/maptoolkit#41]
It should return the `last_edi_1` field from the DB if the pdf exists on S3

**Comment by roblabs** [comment]
### Testing results of the TimeDate parser

Tested on https://hub.docker.com/r/gospatial/atlante, built on Jun 18 (01e7879c576b).

In the 50K Shapefile, the `last_edi_1` values are in the format `2018-07-09T00:00:00.000` and, atlante throws the error

``` console
error generating pdf
	parsing time "2018-07-09T00:00:00.000" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"
```

When changing the data field in PostGIS to `2018-07-09T00:00:00Z`, then PDF generation works.

@gdey

**Comment by ARolek** [comment]
@roblabs the timestamp field is configurable because of this. Check out the `edit_data_format` [here](https://github.com/go-spatial/maptoolkit/tree/master/atlante/grids/postgresql#properties). You will need to use a Go [time layout](https://golang.org/pkg/time/#Parse) so `2006-01-02`.

**Comment by roblabs** [comment]
I may need a little more guidance on the Go format.  I tried the following and they failed

* `edit_data_format = "2006-01-02"`
* `edit_data_format = "2006-01-02T00:00"`
* `edit_data_format = "2006-01-02T00:00:00"`

**Comment by ARolek** [comment]
@roblabs from your earlier comment it sounds like you might have changed the format in the database. Did you change it back to the original format before running the test?

**Comment by gdey** [comment]
@roblabs for the original timestamp try: '2006-01-02T15:04:05.000'

https://godoc.org/time#Parse
https://godoc.org/time#pkg-constants

**Comment by roblabs** [comment]
Recommend re-opening #41.  The issue is that some grid layout data sets will require that we can parse values like `2018-07-09T00:00:00.000`.  As well, this worked earlier this week, so something recently broke.

>  Did you change it back to the original format before running the test?
@Arolek  Yes, and I've been testing with this data value in PostGIS

This value throws this error

![last-edit-fails](https://user-images.githubusercontent.com/118112/59817098-631b5080-92d3-11e9-93ef-69320d248b87.png)

```
error generating pdf
	parsing time "2018-07-09T00:00:00.000" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"
```

---

While this value generated a PDF, `2018-07-09T00:00:00Z`.  My current workaround is to manually edit SQL fields.

![zulu](https://user-images.githubusercontent.com/118112/59817195-da50e480-92d3-11e9-8476-30aedea212f4.png)


---


> @roblabs for the original timestamp try: '2006-01-02T15:04:05.000'
@gdey this is still failing with the setting `edit_data_format = "2006-01-02T15:04:05.000"`

**Comment by gdey** [comment]
@roblabs what was the error it gave with `2006-01-02T15:04:05.000`? I'm getting confused with what is going on. Let's just try one thing at a time. Is the time encoded differently for each row? You said you are manually editing things.

**Comment by roblabs** [comment]
I need to update PostGIS data manually for the grids that are _not_ 5k or 50k.  The 250K does not have columns for `mdg_id` nor `last_edi_1`, so I have to manually update the db for testing.  I have found a workaround, but this means that existing 50k shape file columns would be broken.

>  what was the error it gave with 2006-01-02T15:04:05.000?

Copied from above https://github.com/go-spatial/maptoolkit/issues/41#issuecomment-503662804

---

**In the 50K Shapefile, the `last_edi_1` values are in the format `2018-07-09T00:00:00.000` and, atlante throws the error**

``` console
error generating pdf
	parsing time "2018-07-09T00:00:00.000" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"
```

### Steps to reproduce

```
# using this command
# run atlante
docker run --rm -v "$(pwd)":/mnt -it gospatial/atlante \
  --config /mnt/config.toml                            \
  --mdgid V795G25492                                   \
  --dpi 144 --sheet grid50k -o /mnt/tmp
```

Test from the console

```  console
# get latest docker 
docker pull gospatial/atlante

# get value for mdg_id to know what's in the db
psql grids --command="SELECT last_edi_1 FROM grids.grid50k WHERE mdg_id='V795G25492'"

# put typical value from 50K shape file
# THIS FAILS 
psql grids --command="UPDATE grids.grid50k SET last_edi_1 = '2018-07-09T00:00:00.000' WHERE mdg_id='V795G25492'"


# put value that is a workaround
# This generates a PDF
psql grids --command="UPDATE grids.grid50k SET last_edi_1 = '2018-07-09T00:00:00Z' WHERE mdg_id='V795G25492'"

```

**Comment by roblabs** [comment]
Possible issue with how changes to dates are handled with the psql command or manual editing.  On hold.
