### ISSUE TITLE
Table name is hardcoded as `grids.grid50K`

### ISSUE THREAD

**Issue by roblabs** [go-spatial/maptoolkit#43]
When testing other grid sizes (e.g., 5K, 7.5 minute), the `postgresql.go` is hardcoded at `grid50k`.   That is, only tables named `grid.grid50k` will be query'd.

Does it make sense to _unhardcode_ this to something more generic?

---

https://github.com/go-spatial/maptoolkit/blob/8840b404c4f3b6731be8b410fa05c4eff7e84d4f/atlante/grids/postgresql/postgresql.go#L280

https://github.com/go-spatial/maptoolkit/blob/8840b404c4f3b6731be8b410fa05c4eff7e84d4f/atlante/grids/postgresql/postgresql.go#L323

Related to #42

**Comment by ARolek** [comment]
@roblabs yep, we should move this to something more configurable. The first pass so far has only had to deal with 50k grids and derived 5k grids. Now that we're looking to support more grid types we will need to figure out how to best make this configurable.
