### ISSUE TITLE
Add arbitrary size grids

### ISSUE THREAD

**Issue by roblabs** [go-spatial/maptoolkit#50]
Add support for other sizes, examples only (not in any priority nor request)

* Arbitrary size 1:200000 or smaller
* 1:24K (USGS & USFS) _At a map scale of 1:24000, 1 statute miles on the ground is equivalent to 2.64 inches on the map._
* 1:31,680, _At a map scale of 1:31680, 0.5 statute miles on the ground is equivalent to 1.00 inch on the map._

**Comment by roblabs** [comment]
Tasks
- [ ] Create `atlante/grids/gridxxx' provider
- [ ] Key methods are `CellSize`, `CellForMDGID`
  * https://github.com/go-spatial/maptoolkit/blob/04a967db6132531dfe3856f686a482783d1f163b/atlante/grids/grid5k/grid5k.go#L68
  * https://github.com/go-spatial/maptoolkit/blob/04a967db6132531dfe3856f686a482783d1f163b/atlante/grids/grid5k/grid5k.go#L84
- [ ] update `CellSize` from https://github.com/go-spatial/maptoolkit/blob/60d2f01154a9040e8f7bdeffe610c99f4ec4ee0f/atlante/grids/cell.go#L23

**Comment by gdey** [comment]
For the provider you need to implement the Provider interface:
  * https://github.com/go-spatial/maptoolkit/blob/04a967db6132531dfe3856f686a482783d1f163b/atlante/grids/cell.go#L42-L49

**Comment by gdey** [comment]
This can now be down by specifying the sql to use for the Postgres driver and the new scale value.
