### ISSUE TITLE
Partials support for templates

### ISSUE THREAD

**Issue by gdey** [go-spatial/maptoolkit#7]
At current we are using SVG symbols to refer to other parts to be included in the main template. 
Introduce the following new elements to the template system:

1. get_partial('filename_of_partial') –– This will process the partial if needed generating the file into the assets directory. Returning an object that represents that partial. The Partial Object follows the following interface:
```go
type TemplatePartial {
      // Filename returns the filename of the file in the assets directory
      Filename() string 
     // Path returns the relative path to the file from the work directory
     Path() string
     // GetDefault returns the value for the key if it was set, or the default value
     GetDefault(key string, defaultValue interface{}) interface{}
     // Get returns the value for the key if it was set. If it does not exists exist with 
     // and ErrNonExistantKey Error.
      Get(key string) (interface{}, error)
     // Exists returns if the key is set in the data store
     Exists(key string) bool
}
```
2. partial('filename_of_partial') –– is equvilant to:
```go-template
    {{- $partial := get_partial "partial.svg" -}}
    {{ $partial.Path() }}
```

3. set(key string, value interface{}) –– this allows the current template that is being processed to update its data store. 
4. get(key string) (interface{}, error) –– returns the values from the current templates data store.

The general idea is the first time the partial is requested it will read in that partial process it and (processing any sub included partials) and render the file into the assets directory. Cycles are not allowed, and the system should error if a partial being processed contains a reference to a partial still being processed.

**Comment by gdey** [comment]
After talking with @ARolek, we decided on a different design.

Given the following template directory
```console
template/
   template_one.svg
   template_two.svg
   partials/
       legend.svg
       map.svg
       map.svg.tpl
```

The system will be given a starting SVG. I.E. `template/template_one.svg`
We will look to see if there is a `template/template_one.svg.tpl`.  If there is we will use
that and process the file as a template to generate the `template_one.svg` file to place in the 'work directory.' Otherwise, the file will be copied into the 'work directory.'
If niether files exist the system will error and complain of the missing file.
 
Next, the system will read the SVG file in the `work directory`, (e.g. `template_one.svg`) looking for any element with an `href` or `xlink:href` entry. We will collect each of them start is a relative url. Make sure the list is unique and process each file like the main template was processed. If a file has already be processed, move on to the next one. 

Once all the files have been processed the work directory should be full of svg files the mirror the template directory.

e.g.:
```console
template/
   template_one.svg
   partials/
       legend.svg
       map.svg
```
We can introduce a template directive to set and get values from a per-run global key-value store. 
```
{{ get key }}
or
{{ set key value }}
```

**Comment by jj0hns0n** [comment]
Can we close this now?

**Comment by gdey** [comment]
This is for the code side of the house to build a more robust partials strategy. The current system relies on the worker being able to control and place a lot of things incorrect places. If any of those things are misplaced, things break without errors or warnings. This leads to the possibility of maps being generated without anyone knowing that something is wrong until someone downloads and opens the map.

**Comment by gdey** [comment]
Build partials using "go-templates" define and preloading a templates directory containing "*.tpl" files. This is not as comprehensive as this issue, but get the job done.
