### ISSUE TITLE
Add pdf_url to jobs GET endpoint

### ISSUE THREAD

**Issue by justenPalmer** [go-spatial/maptoolkit#73]
The interface needs a way to get a pdf download for a job that was just processed.

**Comment by gdey** [comment]
This issue brings up interesting design decisions. The way the system is implemented, the pdf_url would be different for each section it shows up. 

When one does a get on the info URL the following structure is return:
```js
{
  "mdgid" : string,
  "sheet_number" : null | number,
  "jobs" : []{
     "mdgid" : string, // the mdgid 
     "sheet_number" : null | number, // the sheet number.
     "sheet_name" : string, // the sheet name
     "status" : {
        "status" : "requested" | "started" | "processing" | "completed" | "failed",
        "stage" : number (0-3), // which stage the job is at
        "total" : number (3),   // the total number of stages
         // description will represent different things depending on status.
         //  for requested, started, completed it will always be empty
         //  for processing it will be the item being processed
         //  for failed it will be the reason it failed
        "description" : string, 
     },
  },
  "pdf_url":  null | url, // if null, pdf has not be generated
  "last_generated" :  null | date, // last time the pdf was generated
  "last_edited" : date,  // last time the data was edited
  "series" : string,
  "geo_json" : geo_json // the geo_json of the bounding box.
  "lat" :  float // the queried lat
  "lng" : float // the queried lng
  "sheet_name": string
}
```

Adding the `pdf_url` to the `job` object could (will with S3) end up providing different urls even though they point to the same pdf.

@jj0hns0n 

However, the more interesting question is what is the `pdf_url` suppose to represent? Is it the pdf that that compleated job generated? 

If this is the user expection then we have to worry about tracking versions of the pdf, and all that entails.

If the expection is that it is the latest PDF, then should we be displaying a download link if there is a job queued or being processed? What about failed jobs? Should the oldest compleated job be available? How do we describe to the user that this is the case?

**Comment by ARolek** [comment]
I talked with @jj0hns0n and we're going to go with the `pdf_url` attribute only being filled out if there is a complete PDF and no job pending for that sheet.

**Comment by jj0hns0n** [comment]
I think it makes sense to _not_ put the pdf_url on the job object, but only
return it in the sheet info endpoint.

>

**Comment by justenPalmer** [comment]
<img width="385" alt="Screen Shot 2019-07-16 at 1 57 07 PM" src="https://user-images.githubusercontent.com/1915862/61550401-33ad5000-aa07-11e9-8d4d-f6f975c40a21.png">

This is meant to resolve the download button that appears on jobs when they are complete. If we only allow the `pdf_url` to be in the sheet it might not be the same one that was generated with the job.

**Comment by justenPalmer** [comment]
Also @gdey, this is for the `jobs/:id/status` endpoint and not the nested jobs within the sheet resource.

**Comment by ARolek** [comment]
@justenPalmer the design we're playing with is that when `pdf_url` is filled in, it's always correct. For example, if a sheet was previously processed, but then a new job started, the `pdf_url` for the sheet would be empty. Once the job is successful the `pdf_url` would then have a value. Would this work on your end?

**Comment by justenPalmer** [comment]
@ARolek, no this will not work on my end. When there is a job that is processing the user is still allowed to get the previously generated sheet with the current interface.

<img width="411" alt="Screen Shot 2019-07-19 at 10 00 40 AM" src="https://user-images.githubusercontent.com/1915862/61552300-4f672500-aa0c-11e9-8dfa-5850a81b51db.png">

The current design with the `pdf_url` always referencing the last generated sheet is perfect for my implementation.

However, this discussion is not relevant to this issue. This issue is referring to the `pdf_url` added to a completely different endpoint (`jobs/:id/status`).

**Comment by gdey** [comment]
Justin, I know you are only interested in the `jobs/:id/status` field; however, this will change the way the job object looks for that end-point v.s. the other endpoints. 

Secondly, since that endpoint is supposed to return the status of any job; if you request a job that completed some time ago, now what is that URL expected behavior? Is the expectation that the URL should point to the pdf that got completed at that point in time? If that is the is the case then we need to manage versions of the PDF. Or should it only return the last pdf that was generated, that seems confusing? The other option would be that only the last completed job has the pdf_url, so now that's a special case...

These are the cases I'm trying to resolve, sure I used the sheet object, but the conceptual issues are the same.

**Comment by justenPalmer** [comment]
@gdey, ah I understand the issue now. The current implementation overwrites the resources on S3 with each new generation. One resource per sheet.

I can ping the sheets endpoint for download URLs for now. That does seem a more correct way of getting the sheet PDF considering this restriction.

I'll have to do something in the interface to manage the expectation of the user. When a job is requested, I'll remove all jobs in progress that for that same sheet.

Currently, what happens if the user requests a job? Does the S3 resource get purged on the start of processing? Or is it overwritten after fully generated? When should I disable download of the previously generated sheet?
