### ISSUE TITLE
/jobs endpoint fails if queue_id is not set in postgres jobs table

### ISSUE THREAD

**Issue by ARolek** [go-spatial/maptoolkit#86]
The `/jobs` endpoint is returning a 500 error with the following message:

```console
failed to get jobs: can't scan into dest[4]: cannot assign NULL to *string
```

I used the query from the `Jobs(...)` method for the postgres provider and added the extra WHERE clause to hunt down the record:

```sql
SELECT 
    job.id,
    job.mdgid,
    job.sheet_number,
    job.sheet_name,
    job.queue_id,
    job.created as enqueued,
    jobstatus.status,
    jobstatus.description,
    jobstatus.created as updated
FROM jobs AS job
LEFT JOIN
( -- find the most recent job status if it exists
	SELECT DISTINCT ON (job_id)
	*
	FROM 
	   statuses
	ORDER BY
	   job_id, id DESC
) AS jobstatus ON jobstatus.job_id = job.id
WHERE job.queue_id IS NULL
ORDER BY jobstatus.id desc
```

This returns the following record:

```console
id |   mdgid    | sheet_number | sheet_name | queue_id |           enqueued            | status | description | updated
----+------------+--------------+------------+----------+-------------------------------+--------+-------------+---------
 48 | F701G30493 |            0 | 50k        |          | 2019-07-25 17:53:40.386024+00 |        |             |
```

So this brings up the following questions / issues:

1. sound a NULL queue_id be supported? If so, scanning should properly handle it.
2. If a NULL queue_id should not be supported then we should add a constraint to the jobs table so it's not nullable.
3. To continue on with #2, I assume this record was written erroneously because there was a problem adding the job to the queue. If that's the case, then we should report the error back to the client.

**Comment by gdey** [comment]
This could also have been a manual job.

**Comment by gdey** [comment]
Yeah, I think the way this happens is if something goes wrong in adding to the queue.
As the job id need to be established before the job is put into the queue, then the job id record can be updated with the queue_id, we have a bit of a chicken and egg problem.
So, it makes sense for queue_id to be a null or empty string. The jobs to handler should handle this correctly. 
You are right, we should output this to the logs when it happens (and I believe we do). 
Do you know if there job_status entrry showing a failure? 
That would be the other thing we should do is add a status record of failed, with the error being failed to enqueue.
